"""Central configuration: tokens, treasury, environment.

Token addresses were verified 2026-07 against two independent sources
(CoinGecko contract lookup + Etherscan token pages). chain.verify_tokens()
re-verifies decimals() and symbol() on-chain at startup and disables any
token that does not match, so a config typo cannot mis-encode a donation.
"""
import os
import secrets

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
DB_PATH = os.path.join(BASE_DIR, "rfps.db")
ENV_PATH = os.path.join(BASE_DIR, ".env")

# All donations flow to this address (TheDAO Security Fund treasury).
# It must be written in exact EIP-55 checksum form: chain.resolve_treasury()
# re-derives the checksum at startup and the app refuses to accept donations
# on any mismatch, so a typo here cannot silently redirect funds.
# Overridable via TREASURY_ADDRESS in .env.
TREASURY_ADDRESS = "0xD5Cf05f24727C83976652E3586c0e26DD39884e9"
TREASURY_LABEL = "TheDAO Security Fund treasury"

CHAIN_ID = 1  # Ethereum mainnet only

# symbol -> (contract address, decimals)
TOKENS = {
    "USDC":   ("0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48", 6),
    "USDT":   ("0xdAC17F958D2ee523a2206206994597C13D831ec7", 6),
    "DAI":    ("0x6B175474E89094C44Da98b954EedeAC495271d0F", 18),
    "USDS":   ("0xdC035D45d973E3EC169d2276DDab16f1e407384F", 18),
    "crvUSD": ("0xf939E0A03FB07F59A73314E73794Be0E57ac1b4E", 18),
    "BOLD":   ("0x6440f144b7e50D6a8439336510312d2F54beB01D", 18),
    "fxUSD":  ("0x085780639CC2cACd35E474e71f4d000e2405d8f6", 18),
}

RPC_ENDPOINTS = [
    "https://ethereum-rpc.publicnode.com",
    "https://eth.llamarpc.com",
    "https://cloudflare-eth.com",
    "https://eth.drpc.org",
]

# ENS Universal Resolver (ENSv2, 2026). The legacy flat registry was
# deprecated in the ENSv2 migration; the Universal Resolver is the
# ENS-sanctioned entry point for all resolution.
ENS_UNIVERSAL_RESOLVER = "0xeEeEEEeE14D718C2B47D9923Deab1335E144EeEe"

# Independent second opinion for ENS resolution (fund-safety cross-check).
ENS_CROSSCHECK_URL = "https://api.ensdata.net/{name}"

SUBMISSIONS_PER_HOUR_PER_IP = 5
LOGIN_ATTEMPTS_PER_MINUTE_PER_IP = 5


def _load_env():
    """Tiny .env loader (no python-dotenv dependency)."""
    data = {}
    if os.path.exists(ENV_PATH):
        with open(ENV_PATH) as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith("#") and "=" in line:
                    k, _, v = line.partition("=")
                    data[k.strip()] = v.strip()
    return data


def _ensure_env():
    """Create .env with generated secrets on first run."""
    env = _load_env()
    changed = False
    if "SECRET_KEY" not in env:
        env["SECRET_KEY"] = secrets.token_hex(32)
        changed = True
    if "ADMIN_PASSWORD" not in env:
        env["ADMIN_PASSWORD"] = "-".join(
            secrets.choice(_WORDS) for _ in range(4
        )) + "-" + str(secrets.randbelow(90) + 10)
        changed = True
    if changed:
        with open(ENV_PATH, "w") as f:
            f.write("# Generated by thedao-rfps. Keep private.\n")
            for k, v in env.items():
                f.write("%s=%s\n" % (k, v))
        os.chmod(ENV_PATH, 0o600)
    return env


_WORDS = (
    "ether summit signal beacon vault ledger anchor cipher merkle nonce "
    "oracle raft galaxy ember quartz falcon harbor lumen praxis zephyr"
).split()

ENV = _ensure_env()
SECRET_KEY = ENV["SECRET_KEY"]
ADMIN_PASSWORD = ENV["ADMIN_PASSWORD"]
RPC_URL_OVERRIDE = ENV.get("RPC_URL", "").strip()
PORT = int(ENV.get("PORT", "4482"))
TREASURY_ADDRESS = ENV.get("TREASURY_ADDRESS", "").strip() or TREASURY_ADDRESS

if RPC_URL_OVERRIDE:
    RPC_ENDPOINTS = [RPC_URL_OVERRIDE] + RPC_ENDPOINTS
