/** JSON Schema (2020-12) of GET /api/initiatives.json. */
export const FEED_JSON_SCHEMA = {
  $schema: "https://json-schema.org/draft/2020-12/schema",
  $id: "/api/initiatives.schema.json",
  title: "TheDAO Security Fund approved initiatives",
  type: "object",
  required: ["schemaVersion", "generatedAt", "count", "totals", "initiatives"],
  properties: {
    schemaVersion: { const: 1 },
    generatedAt: { type: "string", format: "date-time" },
    count: {
      type: "integer",
      minimum: 0,
      description: "Initiatives in this response (after filters)",
    },
    totals: {
      type: "object",
      description: "Across every approved initiative, whatever the filters",
      required: ["goalUsd", "raisedUsd", "backers", "rfps", "grants"],
      properties: {
        goalUsd: { type: "number" },
        raisedUsd: { type: "number" },
        backers: { type: "integer" },
        rfps: { type: "integer" },
        grants: { type: "integer" },
      },
    },
    initiatives: { type: "array", items: { $ref: "#/$defs/initiative" } },
  },
  $defs: {
    initiative: {
      type: "object",
      required: [
        "slug",
        "url",
        "markdownUrl",
        "title",
        "type",
        "categories",
        "status",
        "summary",
        "goalUsd",
        "raisedUsd",
        "pctFunded",
        "backers",
        "donate",
        "pledges",
        "sections",
        "milestones",
        "links",
      ],
      properties: {
        slug: { type: "string" },
        url: { type: "string", format: "uri" },
        markdownUrl: { type: "string", format: "uri" },
        title: { type: "string" },
        type: { enum: ["rfp", "grant"] },
        categories: {
          type: "array",
          description: "Primary first",
          maxItems: 3,
          items: {
            type: "object",
            required: ["slug", "label"],
            properties: { slug: { type: "string" }, label: { type: "string" } },
          },
        },
        status: { enum: ["open", "funded"] },
        summary: { type: "string" },
        goalUsd: { type: "number" },
        raisedUsd: { type: "number", description: "Pledges plus donations" },
        pctFunded: { type: "number", minimum: 0, maximum: 100 },
        backers: { type: "integer", minimum: 0 },
        recipientTeam: { type: ["string", "null"] },
        recipientUrl: { type: ["string", "null"] },
        durationMonths: { type: ["integer", "null"] },
        approvedAt: { type: ["string", "null"], format: "date-time" },
        createdAt: { type: ["string", "null"], format: "date-time" },
        donate: {
          type: ["object", "null"],
          required: ["safeAddress", "chainId", "chain", "tokens", "enabled"],
          properties: {
            safeAddress: { type: "string", pattern: "^0x[0-9a-fA-F]{40}$" },
            chainId: { type: "integer" },
            chain: { type: "string" },
            enabled: { type: "boolean" },
            tokens: {
              type: "array",
              items: {
                type: "object",
                required: ["symbol", "address", "decimals"],
                properties: {
                  symbol: { type: "string" },
                  address: { type: ["string", "null"], description: "null for native ETH" },
                  decimals: { type: "integer" },
                },
              },
            },
          },
        },
        pledges: {
          type: "array",
          items: {
            type: "object",
            required: ["company", "amountUsd", "status"],
            properties: {
              company: { type: "string" },
              amountUsd: { type: "number" },
              status: { enum: ["pledged", "received"] },
            },
          },
        },
        sections: {
          type: "array",
          items: {
            type: "object",
            required: ["key", "heading", "markdown"],
            properties: {
              key: { type: "string" },
              heading: { type: "string" },
              markdown: { type: "string" },
            },
          },
        },
        milestones: {
          type: "array",
          items: {
            type: "object",
            required: ["name", "amountUsd", "adoption", "done", "targetMonth", "criteria"],
            properties: {
              name: { type: "string" },
              amountUsd: { type: "number" },
              adoption: { type: "boolean" },
              done: { type: "boolean" },
              targetMonth: { type: ["string", "null"] },
              criteria: { type: "array", items: { type: "string" } },
            },
          },
        },
        links: { type: "array", items: { type: "string" } },
        details: { type: ["string", "null"], description: "Legacy single-body text" },
      },
    },
  },
} as const;
